### ISSUE TITLE
SparkFunLSM9DS1.cpp exists a "return -1;"

### ISSUE THREAD

**Issue by hoperchan233** [sparkfun/LSM9DS1_Breakout#11]
While utilizing the accompanying library files, I encountered the following error. 

 `*******\Arduino\libraries\Arduino\src\SparkFunLSM9DS1.cpp: In member function 'void LSM9DS1::xgReadBytes(uint8_t, uint8_t*, uint8_t)':
*********Arduino\libraries\Arduino\src\SparkFunLSM9DS1.cpp:1015:10: error: return-statement with a value, in function returning 'void' [-fpermissive]
return -1;
^
*******Arduino\libraries\Arduino\src\SparkFunLSM9DS1.cpp: In member function 'void LSM9DS1::mReadBytes(uint8_t, uint8_t*, uint8_t)':
*******Arduino\libraries\Arduino\src\SparkFunLSM9DS1.cpp:1037:10: error: return-statement with a value, in function returning 'void' [-fpermissive]
return -1;
^
exit status 1`

The provided example program exhibited a similar issue, leaving me in a state of perplexity. The discrepancy I observed pertains to the functions "xgReadBytes" and "mReadBytes" within the "SparkFunLSM9DS1.cpp" file. Both of these functions have been declared as void, yet within the code, there exists a "return -1;" statement. This discrepancy conflicts with the definition of void functions, as they are not intended to return any value.

Upon removing or commenting out the "return -1;" statements within the "xgReadBytes" and "mReadBytes" functions, the code compiled and executed correctly. I would like to mention that I am utilizing IDE version 1.8.19, and I have imported the library from the folder containing the zip file.

**Comment by edspark** [comment]
Agreed, I've fixed the discrepancy between return type and return values, among a few other things in the latest [commit](https://github.com/sparkfun/LSM9DS1_Breakout/commit/3ee0de320d57b116cb784dbdd477e11ae75f9b32). The changes were included in the new zip file.
