### ISSUE TITLE
'printAttitude' was not declared in this scope

### ISSUE THREAD

**Issue by olafurjt13** [sparkfun/LSM9DS1_Breakout#5]
I'm trying to use the SPI example to get data from the LSM9DS1 breakout board but I can't find the printAttitude function anywhere. I've looked into the source files and can't seem to find it. Am I doing something wrong?

**Comment by balamsoto** [comment]
Have same problem

**Comment by bboyho** [comment]
Hi,

I was looking through the issues and noticed that you had an issue compiling. I'm not sure what Arduino IDE version you are using. However, there should be a `printAttitude()` function defined in the **LSM9DS1_Basic_SPI.ino** [ [https://github.com/sparkfun/LSM9DS1_Breakout/blob/master/Libraries/Arduino/examples/LSM9DS1_Basic_SPI/LSM9DS1_Basic_SPI.ino#L222](https://github.com/sparkfun/LSM9DS1_Breakout/blob/master/Libraries/Arduino/examples/LSM9DS1_Basic_SPI/LSM9DS1_Basic_SPI.ino#L222) ] example. Testing out with Arduino IDE v1.8.3 using the library in this repository, I had no issues compiling. I also tried testing it with the GitHub repository for the [SparkFun_LSM9DS1_Arduino_Library](https://github.com/sparkfun/SparkFun_LSM9DS1_Arduino_Library) and there were no issues. 

Try using a different Arduino IDE version or reinstalling the library. Certain versions of the Arduino IDE compile differently and it may be expecting the modular functions before the `void setup(){}` and `void loop(){}` functions.

**Comment by bboyho** [comment]
I just downloaded Arduino IDE v1.6.8 and confirmed that this issue was due to the Arduino IDE version. I recommend that you use a different IDE version to compile like v1.8.5.
