### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/LSM9DS1_Breakout#7]
In two places in SparkFunLSM9DS1.cpp, there is a while-loop with a delay after the Wire.requestFrom() call. That while-loop is not needed and that delay is not needed.

When the Wire.requestFrom() function returns, the I2C transaction has completely finished and the received data is in the receive buffer in the Wire library. The Wire.read() only reads data from that buffer.

**Comment by Grahldg** [comment]
Thanks for pointing this out, they've been removed in the latest commit.
