### ISSUE TITLE
Heading is incorrect

### ISSUE THREAD

**Issue by runchangkang** [sparkfun/LSM9DS1_Breakout#8]
Hello I tried to implement your example basic I2C sample.
The pitch and roll are working fine.
However. the heading data is not changing correctly while rotating the board.
I tried to call calibrateMag() in setup, but the result is still incorrect
Is there any hint I can fix it? Thank you very much

**Comment by Grahldg** [comment]
On further inspection I found that the way the heading was calculated was producing a range greater than 360 degrees.  I have updated the calculation and tested that it does produce values ranging from -180 degrees to 180 degrees.  All examples reflect this in the latest commit.  If you have any questions or are still experiencing any issues, please let me know.
