### ISSUE TITLE
Usage of Wire library

### ISSUE THREAD

**Issue by Koepel** [sparkfun/LSM9DS1_Breakout#9]
The fix for [No need to wait for data after Wire.requestFrom()](https://github.com/sparkfun/LSM9DS1_Breakout/issues/7) was not fully successful.

In the file "https://github.com/sparkfun/LSM9DS1_Breakout/blob/master/Libraries/Arduino/src/SparkFunLSM9DS1.cpp"  there are two leftovers with the variable `timeout` in the functions I2CreadByte() and I2CreadBytes(). 
Those functions also use `Wire.endTransmission(true);` with the comment that a repeated start will be used. That is the other way around, because that parameter should be `false` for a repeated start.

The `timeout` variable can be removed. If you want, you can add a check if data was read from the sensor.

For example:
```
Wire.requestFrom(address, (uint8_t) 1);  // Read one byte from slave register address 
if(Wire.available() != 1)
  return 255; //! Bad! 255 will be misinterpreted as a good value.

```
and:
```
Wire.requestFrom(address, count);  // Read bytes from slave register address 
if(Wire.available() != count)
  return -1;

```

**Comment by edspark** [comment]
Looks like this was silently fixed at some point years ago: https://github.com/sparkfun/LSM9DS1_Breakout/commit/ed83945ff5228455028c26a990edbc3c8d113508
